"""
Conversion engine — HiveQL → PySpark via Claude Sonnet.
Model is read from CLAUDE_MODEL env var (default: claude-sonnet-4-6).
Skill instructions from skills/hiveql_to_pyspark.md are used as the system prompt.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parents[2] / ".env")

import anthropic

MODEL      = os.getenv("CLAUDE_MODEL", "claude-sonnet-4-6")
_SKILLS_DIR = Path(__file__).parents[1] / "skills"


def _skill_body(name: str) -> str:
    """Read skill .md and return body (strips YAML frontmatter)."""
    text = (_SKILLS_DIR / f"{name}.md").read_text(encoding="utf-8")
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) == 3:
            return parts[2].strip()
    return text.strip()


def transform_file(filename: str, hql: str, pipeline: str, metadata: dict) -> dict:
    """Convert a single HiveQL file to PySpark using Claude Sonnet."""
    client        = anthropic.Anthropic()
    system_prompt = _skill_body("hiveql_to_pyspark")

    user_msg = (
        f"Pipeline: {pipeline}\n"
        f"Complexity: {metadata.get('complexity', 'UNKNOWN')}\n"
        f"UDFs present: {', '.join(metadata.get('udf_names', [])) or 'none'}\n"
        f"Filename: {filename}\n\n"
        f"HiveQL source:\n\n{hql}"
    )

    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=system_prompt,
        messages=[{"role": "user", "content": user_msg}],
    )

    spark_python = response.content[0].text.strip()

    # Strip accidental markdown fences if model adds them
    if spark_python.startswith("```"):
        lines        = spark_python.splitlines()
        spark_python = "\n".join(
            l for l in lines if not l.strip().startswith("```")
        ).strip()

    t_count = sum(
        1 for l in spark_python.splitlines()
        if l.strip() and not l.strip().startswith("#")
    )

    return {
        "filename":                filename,
        "python_filename":         filename.replace(".hql", ".py"),
        "source_hql":              hql.strip(),
        "spark_python":            spark_python,
        "transformations_applied": t_count,
        "transformation_log":      [f"Claude Sonnet ({MODEL})"],
    }


def generate_dag(pipeline: str, files: list[str], metadata: dict) -> str:
    """Generate MWAA DAG — template-based, no LLM needed."""
    task_ids = [f.replace(".hql", "").replace("-", "_") for f in files]
    cx       = metadata.get("complexity", "MEDIUM")
    retries  = {"SMALL": 1, "MEDIUM": 2, "LARGE": 3, "COMPLEX": 3}.get(cx, 2)

    task_block = "\n\n".join([
        f'''\
    {tid} = SparkSubmitOperator(
        task_id="{tid}",
        application="s3://dtcm-artifacts/wave1/{pipeline}/{tid}.py",
        conn_id="spark_default",
        retries={retries},
        dag=dag,
    )'''
        for tid in task_ids
    ])

    deps = "\n    ".join(
        f"{task_ids[i-1]} >> {task_ids[i]}"
        for i in range(1, len(task_ids))
    )

    return f'''\
# Generated by convert_subagent — MWAA DAG
# Pipeline: {pipeline} | Complexity: {cx}
# Replaces: Control-M job chain → Apache Airflow DAG

from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator

default_args = {{
    "owner":            "dtcm-migration",
    "depends_on_past":  False,
    "email_on_failure": True,
    "retries":          {retries},
    "retry_delay":      timedelta(minutes=5),
}}

with DAG(
    dag_id="{pipeline}_migration",
    default_args=default_args,
    schedule_interval="0 2 * * *",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["dtcm", "migration", "wave1"],
) as dag:

{task_block}

    {deps}
'''
