"""
Conversion engine — always uses LLMTransformer (Ollama / Llama 3.2).

Model config via .env:
  OLLAMA_MODEL       = llama3.2-vision:latest
  OLLAMA_BASE_URL    = http://localhost:11434/v1
  OLLAMA_TEMPERATURE = 0.1
  OLLAMA_MAX_TOKENS  = 4096
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parents[2] / ".env")

from .future_llm_transformer import LLMTransformer

_transformer = LLMTransformer()
print(f"[conversion_engine] Llama 3.2 via Ollama — model: {os.getenv('OLLAMA_MODEL')}")


def transform_file(filename: str, hql: str, pipeline: str, metadata: dict) -> dict:
    """Transform a single HiveQL file. Returns per-file conversion result."""
    return _transformer.transform(filename, hql, pipeline, metadata)


def generate_dag(pipeline: str, files: list[str], metadata: dict) -> str:
    """Generate MWAA DAG from pipeline definition (template-based)."""
    task_ids = [f.replace(".hql", "").replace("-", "_") for f in files]
    cx       = metadata.get("complexity", "MEDIUM")
    retries  = {"SMALL": 1, "MEDIUM": 2, "LARGE": 3, "COMPLEX": 3}.get(cx, 2)

    task_block = "\n\n".join([
        f'''\
    {tid} = SparkSubmitOperator(
        task_id="{tid}",
        application="s3://dtcm-artifacts/wave1/{pipeline}/{tid}.py",
        conn_id="spark_default",
        retries={retries},
        dag=dag,
    )'''
        for tid in task_ids
    ])

    deps = "\n    ".join(
        f"{task_ids[i-1]} >> {task_ids[i]}"
        for i in range(1, len(task_ids))
    )

    return f'''\
# Generated by convert_agent — MWAA DAG
# Pipeline: {pipeline} | Complexity: {cx}
# Replaces: Control-M job chain → Apache Airflow DAG

from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator

default_args = {{
    "owner":            "dtcm-migration",
    "depends_on_past":  False,
    "email_on_failure": True,
    "retries":          {retries},
    "retry_delay":      timedelta(minutes=5),
}}

with DAG(
    dag_id="{pipeline}_migration",
    default_args=default_args,
    schedule_interval="0 2 * * *",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["dtcm", "migration", "wave1"],
) as dag:

{task_block}

    {deps}
'''
