"""
LLM-based HiveQL → PySpark transformer.
Uses Ollama (local) via the OpenAI-compatible API.

Switch on/off via USE_LLM in .env
Model config:  OLLAMA_MODEL, OLLAMA_BASE_URL, OLLAMA_TEMPERATURE
"""

import os
from openai import OpenAI


SYSTEM_PROMPT = """\
You are an expert data engineer specializing in migrating HiveQL pipelines to production PySpark.

Convert the provided HiveQL file to clean, production-quality PySpark code.

STRICT RULES — follow all of them:

1. File header comment:
   # Generated by convert_agent (Llama 3.2 Vision)
   # Source: <filename>  →  <filename>.py
   # Pipeline: <pipeline>

2. Imports (always include both):
   from pyspark.sql import SparkSession
   from pyspark.sql import functions as F

3. SparkSession setup (always include):
   spark = SparkSession.builder \\
       .config("spark.sql.catalog", "glue_catalog") \\
       .enableHiveSupport().getOrCreate()

4. Replace EVERY ${hiveconf:varname} with:
   varname = spark.conf.get("varname")
   Place all these lines before the transformation code.

5. Aggregate functions — always use F.*:
   SUM(x)    → F.sum("x")
   COUNT(*)  → F.count("*")
   COUNT(x)  → F.count("x")
   AVG(x)    → F.avg("x")
   MIN(x)    → F.min("x")
   MAX(x)    → F.max("x")
   Use .alias("col_name") to preserve column names.

6. INSERT OVERWRITE TABLE target PARTITION(dt=...) SELECT ... FROM source:
   Load source:  df = spark.table("source")
   Apply filters, joins, groupBy, agg on the DataFrame.
   Write:
     result.writeTo("glue_catalog.dtcm.target") \\
         .partitionedBy("dt") \\
         .overwritePartitions()

7. INSERT INTO TABLE target:
   Same as above but end with .append() instead of .overwritePartitions()

8. JOINs:
   source.alias("t").join(other.alias("m"), condition, "inner"/"left")

9. WHERE → .filter()  |  GROUP BY → .groupBy().agg()

10. CREATE TABLE → generate:
    spark.sql(\'\'\'
        CREATE TABLE IF NOT EXISTS glue_catalog.dtcm.table_name
        USING iceberg
        PARTITIONED BY (dt)
        TBLPROPERTIES (\'write.format.default\'=\'parquet\')
    \'\'\')

11. UDFs: keep as function calls — assume they are imported from a udfs module.

OUTPUT: Return ONLY valid Python code. No markdown. No backticks. No explanation text.
"""


class LLMTransformer:
    """Ollama-backed HiveQL → PySpark transformer."""

    def __init__(self) -> None:
        base_url   = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1")
        self.model = os.getenv("OLLAMA_MODEL", "llama3.2-vision:latest")
        self.temp  = float(os.getenv("OLLAMA_TEMPERATURE", "0.1"))
        self.max_t = int(os.getenv("OLLAMA_MAX_TOKENS", "4096"))
        self.client = OpenAI(base_url=base_url, api_key="ollama")

    def transform(self, filename: str, hql: str, pipeline: str, metadata: dict) -> dict:
        """
        Send HiveQL to Ollama, return structured conversion result.
        Same interface as MockTransformer — conversion_engine.py is unaware of which runs.
        """
        user_msg = (
            f"Pipeline: {pipeline}\n"
            f"Complexity: {metadata.get('complexity', 'UNKNOWN')}\n"
            f"UDFs present: {', '.join(metadata.get('udf_names', [])) or 'none'}\n"
            f"Filename: {filename}\n\n"
            f"HiveQL source:\n\n{hql}"
        )

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": user_msg},
            ],
            temperature=self.temp,
            max_tokens=self.max_t,
        )

        spark_python = response.choices[0].message.content.strip()

        # Strip accidental markdown fences if model adds them
        if spark_python.startswith("```"):
            lines = spark_python.splitlines()
            spark_python = "\n".join(
                l for l in lines
                if not l.strip().startswith("```")
            ).strip()

        # Count applied transformations as non-empty, non-comment lines
        t_count = sum(
            1 for l in spark_python.splitlines()
            if l.strip() and not l.strip().startswith("#")
        )

        return {
            "filename":                filename,
            "python_filename":         filename.replace(".hql", ".py"),
            "source_hql":              hql.strip(),
            "spark_python":            spark_python,
            "transformations_applied": t_count,
            "transformation_log":      [f"LLM conversion via {self.model}"],
        }
