/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as OrchestrationRouteImport } from './routes/orchestration'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as ContextGraphRouteImport } from './routes/context-graph'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationRoute = OrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextGraphRoute = ContextGraphRouteImport.update({
  id: '/context-graph',
  path: '/context-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/context-graph': typeof ContextGraphRoute
  '/deployments': typeof DeploymentsRoute
  '/governance': typeof GovernanceRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/skills': typeof SkillsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/context-graph': typeof ContextGraphRoute
  '/deployments': typeof DeploymentsRoute
  '/governance': typeof GovernanceRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/skills': typeof SkillsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/context-graph': typeof ContextGraphRoute
  '/deployments': typeof DeploymentsRoute
  '/governance': typeof GovernanceRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/skills': typeof SkillsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/context-graph'
    | '/deployments'
    | '/governance'
    | '/observability'
    | '/orchestration'
    | '/skills'
    | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/context-graph'
    | '/deployments'
    | '/governance'
    | '/observability'
    | '/orchestration'
    | '/skills'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/context-graph'
    | '/deployments'
    | '/governance'
    | '/observability'
    | '/orchestration'
    | '/skills'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ContextGraphRoute: typeof ContextGraphRoute
  DeploymentsRoute: typeof DeploymentsRoute
  GovernanceRoute: typeof GovernanceRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OrchestrationRoute: typeof OrchestrationRoute
  SkillsRoute: typeof SkillsRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestration': {
      id: '/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof OrchestrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context-graph': {
      id: '/context-graph'
      path: '/context-graph'
      fullPath: '/context-graph'
      preLoaderRoute: typeof ContextGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ContextGraphRoute: ContextGraphRoute,
  DeploymentsRoute: DeploymentsRoute,
  GovernanceRoute: GovernanceRoute,
  ObservabilityRoute: ObservabilityRoute,
  OrchestrationRoute: OrchestrationRoute,
  SkillsRoute: SkillsRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
